""""
report_generator.py

Responsible for generating structured reports from
cleaning and analysis results.

this module does not:
- Read csv
- Clean data
- Analyze data
- Create visulaizations

It only formats existing results into 
a report ictionary.
"""

from typing import Any
from datetime import datetime

def generate_cleaning_report(
        cleaning_summary: dict[str, Any],
) -> dict:
    """
    Generate a cleaning report
    """
    
    report = {
        "Cleaning Summary": {
            "Original Rows": cleaning_summary["original_rows"],
            "Final Rows": cleaning_summary["final_rows"],
            "Duplicates Removed": cleaning_summary["duplicates_removed"],
            "Empty Rows Removed": cleaning_summary["empty_rows_removed"],
        }
    }

    return report




def generate_analysis_report(
        analysis: dict[str, Any],
) -> dict:
    """
    Generate an analysis report.
    """
    
    report = {
        "Dataset Analysis": {
            "Shape": analysis["shape"],
            "Memory usage (MB)": analysis["memory_usage_MB"],
            "Duplicate Rows": analysis["duplicate_rows"],
            "Column Names": analysis["column_names"],
            "Data Types": analysis["data_types"],
            "Missing Values": analysis["missing_values"],
            "Numeric Summary": analysis["numeric_summary"],
            "Categorical summary": analysis["categorical_summary"],
            "Correlation Matrix": analysis["correlation_matrix"],  
        }
    }
    return report


def generate_full_report(
        cleaning_summary: dict[str, Any],
        analysis: dict[str, Any],
) -> dict:
    """
    Combine cleaning and analysis report.
    """
    
    report = {
        "Generated By": "ResearchViz",
        "Generated On": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    report.update(
        generate_cleaning_report(cleaning_summary)
    )

    report.update(
        generate_analysis_report(analysis)
    )

    return report

